apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: songs-service-ingress
  namespace: {{ .Values.namespace }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /songs
spec:
  ingressClassName: nginx
  rules:
    - host: songs
      http:
        paths:
          - path: /api/v1
            pathType: Prefix
            backend:
              service:
                name: songs-service
                port:
                  number: 8081
