---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: songs-db-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: /data/songs-db


---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: songs-db-pvc
  namespace: {{ .Values.namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: manual

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: songs-db
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: songs-db
  template:
    metadata:
      labels:
        app: songs-db
    spec:
      containers:
        - name: songs-db-container
          image: {{ .Values.songsDatabase.image }}
          imagePullPolicy: Never
          env:
            - name: POSTGRES_DB
              value: postgres
            - name: POSTGRES_PORT
              value: "5432"
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: songs-db-secret
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: songs-db-secret
                  key: POSTGRES_PASSWORD
          startupProbe:
            exec:
              command:
                - sh
                - -c
                - |
                  pg_isready -U "$POSTGRES_USER"
            initialDelaySeconds: 10
            periodSeconds: 5
            failureThreshold: 30
          livenessProbe:
            exec:
              command:
                - sh
                - -c
                - |
                  pg_isready -U "$POSTGRES_USER"
            periodSeconds: 10
            failureThreshold: 3
          readinessProbe:
            exec:
              command:
                - sh
                - -c
                - |
                  pg_isready -U "$POSTGRES_USER"
            periodSeconds: 10
            failureThreshold: 3
          ports:
            - containerPort: 5432
              name: song-db
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: songs-db-storage
      volumes:
        - name: songs-db-storage
          persistentVolumeClaim:
            claimName: songs-db-pvc


---
apiVersion: v1
kind: Service
metadata:
  name: songs-db-service
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: songs-db
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  clusterIP: None
