---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: songs-service-app-deployment
  namespace: {{ .Values.namespace }}
  labels:
    app: songs-service-app
spec:
  replicas: {{ .Values.songsService.replicaCount }}
  selector:
    matchLabels:
      app: songs-service-app
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: songs-service-app
    spec:
      containers:
        - name: songs-service-container
          image: songs-service-app:2
          imagePullPolicy: Never
          ports:
            - containerPort: 8081
          startupProbe:
            httpGet:
              path: /actuator/health
              port: 8081
            initialDelaySeconds: 25
            periodSeconds: 30
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8081
            periodSeconds: 10
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8081
            periodSeconds: 10
            failureThreshold: 3
          env:
            - name: SONGS_MS_NAME
              valueFrom:
                configMapKeyRef:
                  name: application-config
                  key: SONGS_MS_NAME
            - name: SONGS_MS_PORT
              valueFrom:
                configMapKeyRef:
                  name: application-config
                  key: SONGS_MS_PORT
            - name: EUREKA_URI
              valueFrom:
                configMapKeyRef:
                  name: application-config
                  key: EUREKA_URI
            - name: ENABLE_EUREKA_CLIENT
              valueFrom:
                configMapKeyRef:
                  name: application-config
                  key: ENABLE_EUREKA_CLIENT
            - name: SONGS_DB_URL
              valueFrom:
                configMapKeyRef:
                  name: application-config
                  key: SONGS_DB_URL
            - name: SONGS_DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: application-config
                  key: SONGS_DB_PORT

---
apiVersion: v1
kind: Service
metadata:
  name: songs-service
  namespace: {{ .Values.namespace }}
spec:
  type: NodePort
  selector:
    app: songs-service-app
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
      nodePort: 30002
