---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: resources-service-app-deployment
  namespace: k8s-java-engineers
  labels:
    app: resources-service-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: resources-service-app
  template:
    metadata:
      labels:
        app: resources-service-app
    spec:
      containers:
        - name: resources-service-container
          image: resources-service-app:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          env:
            - name: RESOURCES_MS_NAME
              value: "resources-ms"
            - name: RESOURCES_MS_PORT
              value: "8080"
            - name: SONGS_MS_URL
              value: "localhost"
            - name: SONGS_MS_PORT
              value: "8081"
            - name: EUREKA_URI
              value: "localhost"
            - name: ENABLE_EUREKA_CLIENT
              value: "false"
            - name: RESOURCES_DB_URL
              value: "resources-db-service"
            - name: RESOURCES_DB_PORT
              value: "5432"

---
apiVersion: v1
kind: Service
metadata:
  name: resources-service
  namespace: k8s-java-engineers
spec:
  type: NodePort
  selector:
    app: resources-service
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30001
