---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: resources-db-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: /data/postgres


---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: resources-db-pvc
  namespace: k8s-java-engineers
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: manual


---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: resources-db
  namespace: k8s-java-engineers
spec:
  replicas: 1
  selector:
    matchLabels:
      app: resources-db
  template:
    metadata:
      labels:
        app: resources-db
    spec:
      containers:
        - name: resources-db-container
          image: postgres:latest
          imagePullPolicy: Never
          env:
            - name: POSTGRES_DB
              value: postgres
            - name: POSTGRES_PORT
              value: "5432"
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: resource-db-secret
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: resource-db-secret
                  key: POSTGRES_PASSWORD
          startupProbe:
            exec:
              command:
                - sh
                - -c
                - |
                  pg_isready -U "$POSTGRES_USER"
            initialDelaySeconds: 10
            periodSeconds: 5
            failureThreshold: 30
          livenessProbe:
            exec:
              command:
                - sh
                - -c
                - |
                  pg_isready -U "$POSTGRES_USER"
            periodSeconds: 10
            failureThreshold: 3
          readinessProbe:
            exec:
              command:
                - sh
                - -c
                - |
                   pg_isready -U "$POSTGRES_USER"
            periodSeconds: 10
            failureThreshold: 3
          ports:
            - containerPort: 5432
              name: resources-db

          volumeMounts:
            - name: db-init-scripts
              mountPath: /docker-entrypoint-initdb.d
              readOnly: true
            - mountPath: /var/lib/postgresql/data
              name: resources-db-storage
      volumes:
        - name: db-init-scripts
          configMap:
            name: resources-db-init-scripts
        - name: resources-db-storage
          persistentVolumeClaim:
            claimName: resources-db-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: resources-db-service
  namespace: k8s-java-engineers
spec:
  selector:
    app: resources-db
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  clusterIP: None
