---
apiVersion: v1
kind: Secret
metadata:
  name: resource-db-secret
  namespace: k8s-java-engineers
data:
  POSTGRES_USER: cG9zdGdyZXM=
  POSTGRES_PASSWORD: cG9zdGdyZXM=

---
apiVersion: v1
kind: Secret
metadata:
  name: songs-db-secret
  namespace: k8s-java-engineers
data:
  POSTGRES_USER: cG9zdGdyZXM=
  POSTGRES_PASSWORD: cG9zdGdyZXM=