---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: songs-service-app-deployment
  namespace: k8s-java-engineers
  labels:
    app: songs-service-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: songs-service-app
  template:
    metadata:
      labels:
        app: songs-service-app
    spec:
      containers:
        - name: songs-service-container
          image: songs-service-app:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8081
          env:
            - name: SONGS_MS_NAME
              value: "songs-ms"
            - name: SONGS_MS_PORT
              value: "8081"
            - name: EUREKA_URI
              value: "localhost"
            - name: ENABLE_EUREKA_CLIENT
              value: "false"
            - name: SONGS_DB_URL
              value: "songs-db-service"
            - name: SONGS_DB_PORT
              value: "5432"

---
apiVersion: v1
kind: Service
metadata:
  name: songs-service
  namespace: k8s-java-engineers
spec:
  type: NodePort
  selector:
    app: songs-service
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
      nodePort: 30002
