---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: songs-db-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: /data/postgres


---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: songs-db-pvc
  namespace: k8s-java-engineers
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: manual


---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: songs-db
  namespace: k8s-java-engineers
spec:
  replicas: 1
  selector:
    matchLabels:
      app: songs-db
  template:
    metadata:
      labels:
        app: songs-db
    spec:
      containers:
        - name: songs-db-container
          image: postgres:latest
          imagePullPolicy: Never
          env:
            - name: POSTGRES_DB
              value: postgres
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: postgres
            - name: POSTGRES_PORT
              value: "5432"
          ports:
            - containerPort: 5432
              name: song-db

          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: songs-db-storage
      volumes:
        - name: songs-db-storage
          persistentVolumeClaim:
            claimName: songs-db-pvc


---
apiVersion: v1
kind: Service
metadata:
  name: songs-db-service
  namespace: k8s-java-engineers
spec:
  selector:
    app: songs-db
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  clusterIP: None
